CREATE TABLE IF NOT EXISTS USERS (id IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL);
TRUNCATE TABLE USERS;

INSERT INTO USERS (name) VALUES ('Imad');
INSERT INTO USERS (name) VALUES ('Saad');
INSERT INTO USERS (name) VALUES ('Mouaad');